# Generated by Django 5.2.12 on 2026-06-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescargaCombustible',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('volumen_descargado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nivel_antes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nivel_despues', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Descarga de Combustible',
                'verbose_name_plural': 'Descargas de Combustible',
                'db_table': 'descargas_combustible',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('capacidad_maxima', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nivel_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nivel_minimo_alerta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tanque',
                'verbose_name_plural': 'Tanques',
                'db_table': 'tanques',
                'ordering': ['sucursal', 'tipo_combustible'],
            },
        ),
    ]
