# Generated by Django 6.0.3 on 2026-05-25 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0007_sucursal_tipos_combustible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('capacidad_maxima', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nivel_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nivel_minimo_alerta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanques', to='ventas.sucursal')),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanques', to='ventas.tipocombustible')),
            ],
            options={
                'verbose_name': 'Tanque',
                'verbose_name_plural': 'Tanques',
                'db_table': 'tanques',
                'ordering': ['sucursal', 'tipo_combustible'],
            },
        ),
        migrations.CreateModel(
            name='DescargaCombustible',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('volumen_descargado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nivel_antes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nivel_despues', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descargas_registradas', to=settings.AUTH_USER_MODEL)),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='inventario.tanque')),
            ],
            options={
                'verbose_name': 'Descarga de Combustible',
                'verbose_name_plural': 'Descargas de Combustible',
                'db_table': 'descargas_combustible',
                'ordering': ['-fecha'],
            },
        ),
    ]
