# Generated by Django 5.2.12 on 2026-06-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='descargacombustible',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descargas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tanque',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanques', to='ventas.sucursal'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='tipo_combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanques', to='ventas.tipocombustible'),
        ),
        migrations.AddField(
            model_name='descargacombustible',
            name='tanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='inventario.tanque'),
        ),
    ]
