# Generated by Django 5.2.12 on 2026-06-22 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_oc', models.CharField(help_text='Ej: OC-9890', max_length=20, unique=True)),
                ('proveedor', models.CharField(default='YPFB Corporación', max_length=100)),
                ('volumen_solicitado', models.DecimalField(decimal_places=2, help_text='Cantidad en Litros', max_digits=10)),
                ('precio_unitario_compra', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADA', 'Pago Conciliado / Autorizada para Recojo'), ('COMPLETADA', 'Combustible Entregado en Surtidor'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='ventas.tipocombustible')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'db_table': 'ordenes_compra',
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Electrónica SIGMA / Banco Unión'), ('DEPOSITO', 'Depósito en Ventanilla Bancaria'), ('QR', 'Pago por QR Institucional del Estado')], default='TRANSFERENCIA', max_length=20)),
                ('nro_referencia', models.CharField(help_text='Código de transacción o número de depósito', max_length=100)),
                ('comprobante_digital', models.FileField(blank=True, null=True, upload_to='comprobantes_proveedores/')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('orden_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_asociado', to='inventario.ordencompra')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'db_table': 'pagos_proveedores',
            },
        ),
    ]
