# Generated by Django 5.2.12 on 2026-06-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_ordencompra_pagoproveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={},
        ),
        migrations.RenameField(
            model_name='ordencompra',
            old_name='precio_unitario_compra',
            new_name='precio_unitario',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='codigo_oc',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='volumen_solicitado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='ordencompra',
            table=None,
        ),
    ]
