# Generated by Django 5.2.12 on 2026-06-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_ordencompra_options_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='codigo_oc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='nro_referencia',
            field=models.CharField(blank=True, help_text='Código de transacción o número de depósito', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='ordencompra',
            unique_together={('tipo_combustible', 'codigo_oc')},
        ),
    ]
