# Generated by Django 5.2.12 on 2026-06-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_ordencompra_codigo_oc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterUniqueTogether(
            name='ordencompra',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='codigo_oc',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
