# Generated by Django 5.2.12 on 2026-06-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_ordencompra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoproveedor',
            name='comprobante_digital',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_pagos/'),
        ),
    ]
