# Generated by Django 6.0.3 on 2026-06-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('inventario', '0006_alter_pagoproveedor_comprobante_digital'),
    ]

    operations = [
    ]
