# Generated by Django 5.2.12 on 2026-05-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='consolidado',
            field=models.BooleanField(default=False),
        ),
    ]
