# Generated by Django 5.2.12 on 2026-05-30 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPrepago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('litros', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estado', models.CharField(choices=[('CREADA', 'Creada'), ('PAGADA', 'Pagada'), ('EXPIRADA', 'Expirada'), ('UTILIZADA', 'Utilizada')], default='CREADA', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_data', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_prepago', to='ventas.cliente')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_prepago', to='ventas.sucursal')),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_prepago', to='ventas.tipocombustible')),
            ],
            options={
                'verbose_name': 'Orden de Prepago',
                'verbose_name_plural': 'Órdenes de Prepago',
                'db_table': 'ordenes_prepago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
