# Generated by Django 5.2.12 on 2026-05-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_compracombustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='client_request_id',
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True, unique=True),
        ),
    ]
