# Generated by Django 5.2.12 on 2026-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ordenprepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenprepago',
            name='fecha_uso',
        ),
        migrations.RemoveField(
            model_name='ordenprepago',
            name='qr_data',
        ),
        migrations.RemoveField(
            model_name='ordenprepago',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='ordenprepago',
            name='comprobante_pdf',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='ordenprepago',
            name='numero_orden',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ordenprepago',
            name='precio_por_litro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio congelado al momento de la compra', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordenprepago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO_PAGO', 'Procesando Pago'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenprepago',
            name='litros',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
