# Generated by Django 5.2.12 on 2026-05-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_sucursal_latitud_alter_sucursal_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isla',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='isla',
            unique_together={('numero', 'sucursal')},
        ),
    ]
