# Generated by Django 6.0.3 on 2026-05-19 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_empresa_usuario_empresa'),
        ('ventas', '0002_alter_sucursal_latitud_alter_sucursal_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='tipocombustible',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_combustible', to='usuarios.empresa'),
        ),
    ]
