# Generated by Django 5.2.12 on 2026-06-04 00:04
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_sucursal_empresa'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
    ]