# Generated by Django 5.2.12 on 2026-06-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_sucursal_empresa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipocombustible',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tipocombustible',
            name='tipo',
            field=models.CharField(choices=[('GASOLINA_ESPECIAL', 'Gasolina Especial'), ('GASOLINA_PREMIUM', 'Gasolina Premium'), ('DIESEL', 'Diésel Oil'), ('GNV', 'Gas Natural Vehicular')], max_length=30, unique=True),
        ),
        migrations.RemoveField(
            model_name='tipocombustible',
            name='empresa',
        ),
    ]
