# Generated by Django 5.2.12 on 2026-05-31 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_ordenprepago_fecha_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='orden_prepago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.ordenprepago'),
        ),
        migrations.AlterField(
            model_name='ordenprepago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO_PAGO', 'Procesando Pago'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Fallido'), ('DESPACHADO', 'Despachado'), ('RECHAZADO', 'Rechazado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('QR', 'Pago QR'), ('CREDITO_FLEET', 'Crédito Fleet'), ('PREPAGO', 'Prepago')], max_length=20),
        ),
    ]
