# Generated by Django 5.2.12 on 2026-06-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocombustible',
            name='costo_litro',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de compra por litro para calcular ganancias', max_digits=10),
        ),
    ]