# Generated by Django 6.0.3 on 2026-05-20 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_empresa_usuario_empresa'),
        ('ventas', '0003_sucursal_empresa_tipocombustible_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.empresa'),
        ),
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_clientes', to='ventas.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_clientes', to='usuarios.empresa')),
            ],
            options={
                'verbose_name': 'Cliente de Empresa',
                'verbose_name_plural': 'Clientes de Empresas',
                'db_table': 'empresa_clientes',
                'unique_together': {('empresa', 'cliente')},
            },
        ),
    ]
