# Generated by Django 6.0.3 on 2026-05-31 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_vehiculo'),
        ('ventas', '0004_cliente_usuario_link'),
    ]

    operations = [
    ]
