# Generated by Django 5.2.12 on 2026-05-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_isla_numero_alter_isla_unique_together'),
        ('ventas', '0003_vehiculo'),
        ('ventas', '0004_cliente_usuario_link'),
    ]

    operations = [
    ]
