# Generated by Django 6.0.3 on 2026-05-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_cliente_empresa_empresacliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isla',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='isla',
            unique_together={('sucursal', 'numero')},
        ),
    ]
