# Generated by Django 6.0.3 on 2026-06-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente_usuario'),
        ('ventas', '0004_venta_orden_prepago_alter_ordenprepago_estado_and_more'),
    ]

    operations = [
    ]
