# Generated by Django 6.0.3 on 2026-05-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_empresa_usuario_empresa'),
        ('ventas', '0005_alter_isla_numero_alter_isla_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocombustible',
            name='tipo',
            field=models.CharField(choices=[('GASOLINA_ESPECIAL', 'Gasolina Especial'), ('GASOLINA_PREMIUM', 'Gasolina Premium'), ('DIESEL', 'Diésel Oil'), ('GNV', 'Gas Natural Vehicular')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='tipocombustible',
            unique_together={('tipo', 'empresa')},
        ),
    ]
