# Generated by Django 6.0.3 on 2026-06-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_merge_20260602_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenprepago',
            name='precio_por_litro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('QR', 'Pago QR'), ('CREDITO_FLEET', 'Crédito Fleet'), ('PREPAGO', 'Prepago'), ('ONLINE / LPR', 'Online / LPR')], max_length=20),
        ),
    ]
