# Generated by Django 6.0.3 on 2026-06-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente_usuario'),
        ('ventas', '0006_alter_ordenprepago_precio_por_litro_and_more'),
    ]

    operations = [
    ]