# Generated by Django 6.0.3 on 2026-05-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_tipocombustible_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='tipos_combustible',
            field=models.ManyToManyField(blank=True, related_name='sucursales', to='ventas.tipocombustible'),
        ),
    ]
