# Generated by Django 6.0.3 on 2026-06-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_tipocombustible_costo_litro'),
        ('ventas', '0007_merge_20260614_0029'),
    ]

    operations = [
    ]
