# Generated by Django 6.0.3 on 2026-05-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_initial'),
        ('usuarios', '0002_limiteconsumo_and_more'),
    ]

    operations = [
    ]
