# Generated by Django 6.0.3 on 2026-05-25

import django.db.models.deletion
import django.db.models.query_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteConsumo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=10)),
                ('unidad', models.CharField(choices=[('LITROS', 'Litros'), ('MONTO', 'Monto')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_consumo', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limites_creados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limites_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Límite de Consumo',
                'verbose_name_plural': 'Límites de Consumo',
                'db_table': 'limites_consumo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='limiteconsumo',
            constraint=models.UniqueConstraint(
                condition=django.db.models.query_utils.Q(('is_active', True)),
                fields=('cliente', 'tipo'),
                name='uq_limite_activo_cliente_tipo',
            ),
        ),
    ]
