# Generated by Django 6.0.3 on 2026-05-12 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_merge_0002_initial_0002_limiteconsumo_and_more'),
        ('usuarios', '0003_passwordresettoken'),
    ]

    operations = [
    ]
