# Generated by Django 6.0.3 on 2026-05-31 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_acepta_politica_privacidad_at_and_more'),
        ('usuarios', '0004_migrar_limites_a_clientes_ventas'),
    ]

    operations = [
    ]
