# Generated by Django 5.2.12 on 2026-06-02 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario_rol', models.CharField(blank=True, max_length=150, null=True)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('CONSULTAR', 'Consulta'), ('RECUPERACION_CONTRASENA', 'Recuperación de contraseña')], max_length=30)),
                ('estado', models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error')], max_length=20)),
                ('modulo_afectado', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='usuarios.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
