# Generated by Django 6.0.3 on 2026-04-16 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Bitácora', 'verbose_name_plural': 'Bitácoras'},
        ),
        migrations.RenameField(
            model_name='bitacora',
            old_name='fecha_hora',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='bitacora',
            old_name='ip_address',
            new_name='direccion_ip',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='usuario_email',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='detalles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='dispositivo',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile')], default='Web', max_length=10),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='modulo_afectado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['-creado_en'], name='bitacora_creado__82cdb8_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['accion'], name='bitacora_accion_401835_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['dispositivo'], name='bitacora_disposi_6a69a8_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['usuario'], name='bitacora_usuario_a680ec_idx'),
        ),
    ]
