# Generated by Django 5.2.12 on 2026-05-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='modulo_afectado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
