# Generated by Django 5.2.12 on 2026-05-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_add_consultar_to_bitacora_acciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('CONSULTAR', 'Consulta'), ('RECUPERACION_CONTRASENA', 'Recuperación de contraseña')], max_length=30),
        ),
    ]
