# Generated by Django 5.2.12 on 2026-05-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_bitacora_descripcion_bitacora_modulo_afectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='usuario_rol',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
