# Generated by Django 6.0.3 on 2026-05-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_alter_bitacora_accion'),
        ('usuarios', '0005_empresa_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='usuarios.empresa'),
        ),
    ]
