# Generated by Django 5.2.12 on 2026-05-25 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSurtidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('FALLA', 'Falla'), ('AUTORIZADO_REMOTO', 'Autorizado Remoto (LPR)')], default='ACTIVO', max_length=20)),
                ('descripcion_falla', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('placa_activa', models.CharField(blank=True, help_text='Placa leída por la cámara LPR que disparó el CU 14', max_length=15, null=True)),
                ('monto_autorizado', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto prepagado inyectado remotamente al surtidor', max_digits=10, max_length=10)),
                ('cliente_activo', models.ForeignKey(blank=True, help_text='Usuario dueño de la compra online activa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_remotos_actuales', to=settings.AUTH_USER_MODEL)),
                ('lado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_surtidor', to='ventas.lado')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Surtidor',
                'verbose_name_plural': 'Estados de Surtidores',
                'db_table': 'estados_surtidores',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoSurtidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado', to=settings.AUTH_USER_MODEL)),
                ('lado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='ventas.lado')),
            ],
            options={
                'db_table': 'historial_estados_surtidores',
                'ordering': ['-fecha'],
            },
        ),
    ]
