# Generated by Django 5.2.12 on 2026-06-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSurtidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('FALLA', 'Falla')], default='ACTIVO', max_length=20)),
                ('descripcion_falla', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Surtidor',
                'verbose_name_plural': 'Estados de Surtidores',
                'db_table': 'estados_surtidores',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoSurtidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial_estados_surtidores',
                'ordering': ['-fecha'],
            },
        ),
    ]
