# Generated by Django 5.2.12 on 2026-06-04 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosurtidor',
            name='cliente_activo',
            field=models.ForeignKey(blank=True, help_text='Usuario dueño de la compra online activa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_remotos_actuales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estadosurtidor',
            name='monto_autorizado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto prepagado inyectado remotamente al surtidor', max_digits=10),
        ),
        migrations.AddField(
            model_name='estadosurtidor',
            name='placa_activa',
            field=models.CharField(blank=True, help_text='Placa leída por la cámara LPR que disparó el CU 14', max_length=15, null=True),
        ),
    ]
